export const COMPANY_KEYS = ['ecocat', 'pranav', 'sanden', 'sata'] as const;
export type CompanyKey = typeof COMPANY_KEYS[number];

export const COMPANIES: Record<CompanyKey, { name: string; logo: string }> = {
  ecocat: { name: 'Ecocat India Pvt. Ltd.', logo: '/logos/ecologo.jpg' },
  pranav: { name: 'Pranav Vikas Pvt. Ltd.', logo: '/logos/pranavlogo.png' },
  sanden: { name: 'Sanden Vikas Pvt. Ltd.', logo: '/logos/sandenlogo.jpg' },
  sata: { name: 'SATA Vikas Pvt. Ltd.', logo: '/logos/satalogo.webp' },
};

export const BUILT_IN_USERS = [
  { pin: '2701', name: 'CIO / Group IT Head', role: 'CIO', department: 'IT', companyKey: null },
  { pin: '2702', name: 'IT Manager - ECOCAT', role: 'IT_MANAGER', department: 'IT', companyKey: 'ecocat' },
  { pin: '2703', name: 'IT Manager - PRANAV', role: 'IT_MANAGER', department: 'IT', companyKey: 'pranav' },
  { pin: '2704', name: 'IT Manager - SANDEN', role: 'IT_MANAGER', department: 'IT', companyKey: 'sanden' },
  { pin: '2705', name: 'IT Manager - SATA', role: 'IT_MANAGER', department: 'IT', companyKey: 'sata' },
  { pin: '3702', name: 'STQM Manager - ECOCAT', role: 'STQM_MANAGER', department: 'STQM', companyKey: 'ecocat' },
  { pin: '3703', name: 'STQM Manager - PRANAV', role: 'STQM_MANAGER', department: 'STQM', companyKey: 'pranav' },
  { pin: '3704', name: 'STQM Manager - SANDEN', role: 'STQM_MANAGER', department: 'STQM', companyKey: 'sanden' },
  { pin: '3705', name: 'STQM Manager - SATA', role: 'STQM_MANAGER', department: 'STQM', companyKey: 'sata' },
  { pin: '3801', name: 'HR Manager', role: 'HR_MANAGER', department: 'HR', companyKey: null },
  { pin: '4901', name: 'Admin / Facilities', role: 'ADMIN_FACILITIES', department: 'ADMIN', companyKey: null },
  { pin: '5012', name: 'Legal / Compliance', role: 'LEGAL', department: 'LEGAL', companyKey: null },
  { pin: '9001', name: 'MD / CEO', role: 'MD_CEO', department: 'FINANCE', companyKey: null },
  { pin: '1101', name: 'IT Executive - ECOCAT', role: 'IT_EXECUTIVE', department: 'IT', companyKey: 'ecocat' },
  { pin: '1102', name: 'IT Executive - PRANAV', role: 'IT_EXECUTIVE', department: 'IT', companyKey: 'pranav' },
  { pin: '1103', name: 'IT Executive - SANDEN', role: 'IT_EXECUTIVE', department: 'IT', companyKey: 'sanden' },
  { pin: '1104', name: 'IT Executive - SATA', role: 'IT_EXECUTIVE', department: 'IT', companyKey: 'sata' },
  { pin: '1201', name: 'HR Executive - ECOCAT', role: 'HR_EXECUTIVE', department: 'HR', companyKey: 'ecocat' },
  { pin: '1202', name: 'HR Executive - PRANAV', role: 'HR_EXECUTIVE', department: 'HR', companyKey: 'pranav' },
  { pin: '1203', name: 'HR Executive - SANDEN', role: 'HR_EXECUTIVE', department: 'HR', companyKey: 'sanden' },
  { pin: '1204', name: 'HR Executive - SATA', role: 'HR_EXECUTIVE', department: 'HR', companyKey: 'sata' },
];

export const ROLE_ACCESS: Record<string, { access: string; tabs: string[] }> = {
  CIO: { access: 'write', tabs: ['overview', 'my-controls', 'docs', 'review', 'certificates', 'users', 'trend', 'log'] },
  IT_MANAGER: { access: 'write', tabs: ['overview', 'my-controls', 'docs', 'review', 'certificates', 'users', 'trend', 'log'] },
  STQM_MANAGER: { access: 'write', tabs: ['overview', 'my-controls', 'docs', 'review', 'certificates', 'users', 'trend', 'log'] },
  HR_MANAGER: { access: 'write', tabs: ['overview', 'my-controls', 'docs', 'review', 'certificates', 'users', 'trend', 'log'] },
  ADMIN_FACILITIES: { access: 'write', tabs: ['overview', 'my-controls', 'docs', 'certificates', 'users', 'trend', 'log'] },
  LEGAL: { access: 'write', tabs: ['overview', 'my-controls', 'docs', 'certificates', 'users', 'trend', 'log'] },
  MD_CEO: { access: 'read', tabs: ['exec', 'trend', 'log'] },
  IT_EXECUTIVE: { access: 'maker', tabs: ['overview', 'my-controls', 'docs', 'trend', 'log'] },
  HR_EXECUTIVE: { access: 'maker', tabs: ['overview', 'my-controls', 'docs', 'trend', 'log'] },
};

export const CONTROL_CATEGORIES = {
  CLAUSES: { id: 'clauses', name: 'Clauses 4-10 (Mandatory)', objective: 'The mandatory requirements for establishing, implementing, maintaining, and continually improving the ISMS.' },
  ANNEX_A_5: { id: 'annex_a_5', name: 'A.5 Organisational Controls', objective: 'To establish governance, define responsibilities, and ensure effective management of information security through clear policies, accountability, and collaboration.' },
  ANNEX_A_6: { id: 'annex_a_6', name: 'A.6 People Controls', objective: 'To ensure employees and contractors understand and fulfill their information security responsibilities through effective management, awareness, and training.' },
  ANNEX_A_7: { id: 'annex_a_7', name: 'A.7 Physical Controls', objective: 'To prevent unauthorized physical access, damage, and interference to an organization\'s information and assets.' },
  ANNEX_A_8: { id: 'annex_a_8', name: 'A.8 Technological Controls', objective: 'To ensure the secure use of technology to protect information and manage cybersecurity risks.' },
};

export const EVIDENCE_TYPES = ['Policy', 'Procedure', 'Register', 'Report', 'Screenshot', 'Certificate', 'Minutes', 'Contract', 'Training Records', 'Audit Report', 'Other'];

export const CONTROL_DEFINITIONS = [
  { controlId: 'A.5.1', label: 'Policies for Information Security', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.2', label: 'Information security roles and responsibilities', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.3', label: 'Segregation of duties', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.4', label: 'Management responsibilities', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.5', label: 'Contact with authorities', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.6', label: 'Contact with special interest groups', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.7', label: 'Threat intelligence', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.8', label: 'Information security in project management', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.9', label: 'Inventory of information and other associated assets', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.10', label: 'Acceptable use of information and other associated assets', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.11', label: 'Return of assets', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.12', label: 'Classification of information', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.13', label: 'Labelling of information', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.14', label: 'Information transfer', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.15', label: 'Access Control', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.16', label: 'Identity Management', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.17', label: 'Authentication Information', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.18', label: 'Access Rights', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.19', label: 'Information security in supplier relationships', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.20', label: 'Addressing information security within supplier agreements', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.21', label: 'Managing information security in the ICT Supply chain', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.22', label: 'Monitoring, review and change management of supplier services', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.23', label: 'Information Security for use of cloud service', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.24', label: 'Information security incident management planning and preparation', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.25', label: 'Assessment and decision on information security events', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.26', label: 'Response to information security incidents', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.27', label: 'Learning from information security incidents', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.28', label: 'Collection of evidence', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.29', label: 'Information security during disruption', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.30', label: 'ICT readiness for business continuity', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.31', label: 'Legal, statutory, regulatory and contractual requirements', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.32', label: 'Intellectual property rights', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.33', label: 'Protection of records', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.34', label: 'Privacy and protection of personal identifiable information (PII)', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.35', label: 'Independent review of information security', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.36', label: 'Compliance with policies, rules and standards for information security', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.5.37', label: 'Documented operating procedures', category: 'annex_a_5', subCategory: null },
  { controlId: 'A.6.1', label: 'Screening', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.2', label: 'Terms and conditions of employment', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.3', label: 'Information security awareness, education and training', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.4', label: 'Disciplinary process', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.5', label: 'Responsibilities after termination or change of employment', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.6', label: 'Confidentiality or non-disclosure agreements', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.7', label: 'Remote working', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.6.8', label: 'Information security event reporting', category: 'annex_a_6', subCategory: null },
  { controlId: 'A.7.1', label: 'Physical security perimeters', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.2', label: 'Physical entry', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.3', label: 'Securing offices, rooms and facilities', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.4', label: 'Physical security monitoring', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.5', label: 'Protecting against physical and environmental threats', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.6', label: 'Working in secure areas', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.7', label: 'Clear desk and clear screen', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.8', label: 'Equipment siting and protection', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.9', label: 'Security of assets off-premises', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.10', label: 'Storage media', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.11', label: 'Supporting utilities', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.12', label: 'Cabling security', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.13', label: 'Equipment maintenance', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.7.14', label: 'Secure disposal or re-use of equipment', category: 'annex_a_7', subCategory: null },
  { controlId: 'A.8.1', label: 'User end point devices', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.2', label: 'Privileged access rights', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.3', label: 'Information access restriction', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.4', label: 'Access to source code', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.5', label: 'Secure authentication', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.6', label: 'Capacity management', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.7', label: 'Protection against malware', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.8', label: 'Management of technical vulnerabilities', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.9', label: 'Configuration management', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.10', label: 'Information deletion', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.11', label: 'Data masking', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.12', label: 'Data leakage prevention', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.13', label: 'Information backup', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.14', label: 'Redundancy of information processing facilities', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.15', label: 'Logging', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.16', label: 'Monitoring activities', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.17', label: 'Clock synchronization', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.18', label: 'Use of privileged utility programs', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.19', label: 'Installation of software on operational systems', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.20', label: 'Networks security', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.21', label: 'Security of network services', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.22', label: 'Segregation of networks', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.23', label: 'Web filtering', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.24', label: 'Use of cryptography', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.25', label: 'Secure development life cycle', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.26', label: 'Application security requirements', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.27', label: 'Secure system architecture and engineering principles', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.28', label: 'Secure coding', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.29', label: 'Security testing in development and acceptance', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.30', label: 'Outsourced development', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.31', label: 'Separation of development, test and production environments', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.32', label: 'Change management', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.33', label: 'Test information', category: 'annex_a_8', subCategory: null },
  { controlId: 'A.8.34', label: 'Protection of information systems during audit testing', category: 'annex_a_8', subCategory: null },
];